/* AUTO-GENERATED by simulator/scripts/dump-core-fixtures.py — DO NOT EDIT.
   Golden data extracted from /home/user/a/scripts/figures/ (GDD §10-A). */
export const fig10 = {
 "days": [
  {
   "val": 97.8999999999997,
   "vah": 101.79999999999947,
   "poc": 99.99999999999957
  },
  {
   "val": 102.49999999999969,
   "vah": 106.39999999999947,
   "poc": 104.29999999999959
  },
  {
   "val": 107.39999999999968,
   "vah": 111.29999999999946,
   "poc": 109.99999999999953
  },
  {
   "val": 107.79999999999963,
   "vah": 112.09999999999938,
   "poc": 109.59999999999953
  },
  {
   "val": 108.69999999999985,
   "vah": 110.49999999999974,
   "poc": 109.4999999999998
  },
  {
   "val": 101.29999999999968,
   "vah": 105.19999999999946,
   "poc": 103.59999999999955
  }
 ],
 "relationships": [
  "higher",
  "higher",
  "overlapping",
  "inside",
  "lower"
 ]
} as const;
