#!/usr/bin/env python3
"""Golden-fixture dumper for @auction/core (GDD §10-A golden-file parity).

Executes the Python reference scripts in /home/user/a/scripts/figures/ with
Figure.savefig patched to a no-op (no repo side effects), extracts the exact
synthetic datasets they computed, derives the expected structural quantities,
and writes TypeScript fixture modules into src/lib/core/__fixtures__/.

Expected values are computed here with the SAME floating-point operation order
as the TS implementations (plain left-to-right sums, not numpy pairwise), so
row-index parity is bit-exact.

Usage: python3 scripts/dump-core-fixtures.py
"""

import json
import math
import os
import runpy

import numpy as np
import matplotlib
matplotlib.use('Agg')
from matplotlib.figure import Figure

FIG_DIR = '/home/user/a/scripts/figures'
OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       'src', 'lib', 'core', '__fixtures__')
os.makedirs(OUT_DIR, exist_ok=True)

# ---------------------------------------------------------------- helpers

def run_fig(name, capture_lognormal=False):
    """Run a figure script with savefig disabled; return its globals."""
    orig_savefig = Figure.savefig
    Figure.savefig = lambda self, *a, **k: None
    captured = []
    orig_lognormal = np.random.lognormal
    if capture_lognormal:
        def rec(*a, **k):
            out = orig_lognormal(*a, **k)
            captured.append(out.copy())
            return out
        np.random.lognormal = rec
    try:
        g = runpy.run_path(os.path.join(FIG_DIR, name))
    finally:
        Figure.savefig = orig_savefig
        np.random.lognormal = orig_lognormal
    g['_captured_lognormal'] = captured
    return g


def find_poc(rows):
    """TS findPoc parity: argmax; ties -> closer to profile middle, then lower index."""
    n = len(rows)
    mid = (n - 1) / 2
    best = 0
    for i in range(1, n):
        if rows[i] > rows[best] or (
            rows[i] == rows[best] and abs(i - mid) < abs(best - mid)
        ):
            best = i
    return best


def expand_va(rows, poc, frac=0.70):
    """TS expandValueArea parity (guide Part II §2.2): one row at a time,
    larger wins, tie -> row closer to POC, equidistant tie -> up.
    Sums are plain left-to-right to match TS reduce()."""
    total = 0.0
    for x in rows:
        total += float(x)
    target = total * frac
    lo = hi = poc
    acc = float(rows[poc])
    n = len(rows)
    while acc < target and (lo > 0 or hi < n - 1):
        up = float(rows[hi + 1]) if hi + 1 < n else -math.inf
        dn = float(rows[lo - 1]) if lo - 1 >= 0 else -math.inf
        if up > dn:
            hi += 1
            acc += up
        elif dn > up:
            lo -= 1
            acc += dn
        elif (hi + 1 - poc) <= (poc - (lo - 1)):
            hi += 1
            acc += up
        else:
            lo -= 1
            acc += dn
    return lo, hi


def ts_module(name, payload):
    path = os.path.join(OUT_DIR, name + '.ts')
    body = json.dumps(payload, indent=1)
    with open(path, 'w') as f:
        f.write('/* AUTO-GENERATED by simulator/scripts/dump-core-fixtures.py — DO NOT EDIT.\n'
                '   Golden data extracted from /home/user/a/scripts/figures/ (GDD §10-A). */\n'
                f'export const {name} = {body} as const;\n')
    print('wrote', path)


def flist(a, nd=None):
    a = np.asarray(a, dtype=float).tolist()
    if nd is not None:
        a = [round(x, nd) for x in a]
    return a


# ---------------------------------------------------------------- fig-01
g = run_fig('fig-01-volume-profile-anatomy.py')
vol = g['vol']
poc = find_poc(vol)
assert poc == g['poc_i']
lo, hi = expand_va(vol, poc)
# fig-01's own expansion is one-row ties-up; with float data ties never occur,
# so guide-rule and fig-01 must agree exactly:
assert (lo, hi) == (g['lo'], g['hi']), ((lo, hi), (g['lo'], g['hi']))
ts_module('fig01', {
    'vol': flist(vol),
    'poc': poc, 'val': lo, 'vah': hi,
    'lvn': int(g['lvn_i']), 'hvnSmallPeak': int(g['small_peak_i']),
})

# ---------------------------------------------------------------- fig-02
g = run_fig('fig-02-profile-shapes.py')
profiles = g['profiles']
shape_labels = ['D', 'P', 'b', 'B', 'thin-trend']
ts_module('fig02', {
    'profiles': [
        {'name': g['names'][i], 'shape': shape_labels[i], 'rows': flist(v)}
        for i, (y, v) in enumerate(profiles)
    ],
    'bNeckIndex': int(g['neck']),
    'bPeaks': sorted((int(g['p1']), int(g['p2']))),
})

# ---------------------------------------------------------------- fig-05
g = run_fig('fig-05-day-types.py', capture_lognormal=True)
panels = g['panels']
vols_per_panel = g['_captured_lognormal']
assert len(vols_per_panel) == 6 and all(len(v) == 390 for v in vols_per_panel)
day_types = ['normal', 'normal-variation', 'trend',
             'double-distribution-trend', 'nontrend', 'neutral']
ts_module('fig05', {
    'binw': float(g['binw']),
    'ibMin': int(g['IB_MIN']),
    'panels': [
        {'name': panels[i][0], 'dayType': day_types[i],
         'path': flist(panels[i][2], 6), 'vols': flist(vols_per_panel[i], 6)}
        for i in range(6)
    ],
})

# ---------------------------------------------------------------- fig-06
g = run_fig('fig-06-open-types.py')
ts_module('fig06', {
    'open': float(g['OPEN']),
    'paths': {
        'openDrive': flist(g['p1'], 6),
        'openTestDrive': flist(g['p2'], 6),
        'openRejectionReverse': flist(g['p3'], 6),
        'openAuction': flist(g['p4'], 6),
    },
    'testDriveLowIdx': int(g['low_idx2']),
    'rejectionPeakIdx': int(g['peak_i']),
    'auctionCrossings': int(g['n_cross4']),
})

# ---------------------------------------------------------------- fig-09
g = run_fig('fig-09-excess-vs-poor.py')
vol_L, vol_R = g['vol_L'], g['vol_R']
ts_module('fig09', {
    'excessHigh': flist(vol_L),   # long taper at the top -> excess high
    'poorHigh': flist(vol_R),     # flat plateau top rows -> poor high
    'tailRows': int(g['tail_n']),
    'pocExcess': find_poc(vol_L),
    'pocPoor': find_poc(vol_R),
})

# ---------------------------------------------------------------- fig-10
g = run_fig('fig-10-value-migration.py')
ts_module('fig10', {
    'days': [
        {'val': float(v), 'vah': float(h), 'poc': float(p)}
        for v, h, p in zip(g['VAL'], g['VAH'], g['PC'])
    ],
    # day-over-day relationship of day i vs day i-1, per the fig's assertions
    'relationships': ['higher', 'higher', 'overlapping', 'inside', 'lower'],
})

# ---------------------------------------------------------------- fig-12
g = run_fig('fig-12-vp-tpo-vwap.py')
price, vol, vap = g['price'], g['vol'], g['vap']
poc = find_poc(vap)
assert poc == g['poc_idx']
va_lo, va_hi = expand_va(vap, poc)
tpo_counts = g['tpo_counts']
tpo_poc = find_poc(tpo_counts)
assert tpo_poc == g['tpo_poc_idx']
tpo_lo, tpo_hi = expand_va(tpo_counts, tpo_poc)
ts_module('fig12', {
    'price': flist(price),
    'vol': flist(vol),
    'rowStep': float(g['ROW']),
    'minPrice': float(g['lo']),
    'nRows': int(g['nrows']),
    'poc': poc, 'val': va_lo, 'vah': va_hi,
    'tpoPoc': tpo_poc, 'tpoVal': tpo_lo, 'tpoVah': tpo_hi,
    'maxTpoStack': int(tpo_counts.max()),
    'vwapEnd': float(g['vwap'][-1]),
    'sdEnd': float(g['sd'][-1]),
    'ibHigh': float(price[:60].max()),
    'ibLow': float(price[:60].min()),
})

print('all fixtures written')
